Repository upbound/xgql, pull requests merged in 2021-06, with the labels that each got.

#73 Compress HTTP reponses
  cmd/xgql/main.go
Labels: backport release-0.1, cla-signed, size/XS

#74 Propagate handy GitHub workflows
  .github/workflows/backport.yml
  .github/workflows/commands.yml
Labels: cla-signed, size/M

#77 Add Google Cloud Trace Exporter option
  cmd/xgql/main.go
  go.mod
  go.sum
  internal/opentelemetry/tracing.go
Labels: backport release-0.1, cla-signed, size/M

#79 Backport 77 to release 0.1
  cmd/xgql/main.go
  go.mod
  go.sum
  internal/opentelemetry/tracing.go
Labels: cla-signed, size/M
