Repository upbound/xgql, pull requests merged in 2022-09, with the labels that each got.

#93 Create a token secret for our service account
  README.md
  cluster/local/service-account.yaml
Labels: size/M

#97 Return `NULL` for several cases when related objects are not found.
  internal/graph/generated/generated.go
  internal/graph/model/common.go
  internal/graph/model/common_test.go
  internal/graph/model/composite.go
  internal/graph/model/composite_test.go
  internal/graph/model/generated.go
  internal/graph/model/managed.go
  internal/graph/model/managed_test.go
  internal/graph/resolvers/composite.go
  internal/graph/resolvers/composite_test.go
  internal/graph/resolvers/managed.go
  internal/graph/resolvers/managed_test.go
  internal/graph/resolvers/query.go
  schema/common.gql
  schema/composite.gql
Labels: size/XXL

#98 Setup CI to publish GraphQL schema to Apollo Studio
  .github/workflows/ci.yml
  .graphql-schema-linterrc
  .prettierrc.json
  Makefile
  lint-schema/package.json
  package.json
  yarn.lock
Labels: size/L

#100 Fix promote pointing at master instead of main
  .github/workflows/ci.yml
Labels: size/XS

#101 Add default AWS region to workflows
  .github/workflows/ci.yml
  .github/workflows/promote.yml
Labels: size/XS

#102 Use us-west-2 as AWS region in commit
  .github/workflows/ci.yml
  .github/workflows/promote.yml
Labels: size/XS

#103 Use public Upbound buckets for releases and charts
  Makefile
Labels: size/XS

#105 Add `crossplaneResourceTree` to get a list of all descendantes of a given XRM Resource.
  internal/graph/generated/generated.go
  internal/graph/model/generated.go
  internal/graph/resolvers/query.go
  internal/graph/resolvers/query_test.go
  schema/queries.gql
Labels: size/XL
